# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_auto_20170310_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='points_received',
            new_name='points_collected',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
    ]
