# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0003_auto_20170315_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='points_collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='points_to_give',
            field=models.IntegerField(default=100),
        ),
    ]
